# Generated by Django 3.0.2 on 2020-02-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='misa_like_it',
            field=models.IntegerField(default=0),
        ),
    ]
